# Site settings
name: Baptiste Thevelein
title: Baptiste Thevelein
description: Je crée et accompagne des projets dans l'ESS et les médias.
url: https://baptistethevelein.fr
baseurl: ''
email: baptiste@thevelein.fr
cover: https://baptistethevelein.fr/img/cover.png
logo: https://baptistethevelein.fr/img/emojis/male-technologist.png
resume: https://baptistethevelein.fr/cv.pdf
social:
  - title: e-mail
    url: mailto:theveleinbaptiste@gmail.com
  - title: twitter
    url: https://twitter.com/bthevelein
  - title: instagram
    url: https://instagram.com/bthevelein
  - title: linkedin
    url: https://www.linkedin.com/in/bthevelein/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
