# Site settings
name: Baptiste Thevelein
title: Baptiste Thevelein
description: Création de sites internet, identités visuelles, médias.
url: https://baptistethevelein.fr
baseurl: ''
email: baptiste@thevelein.fr
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://baptistethevelein.fr/cv.pdf
social:
  - title: email
    url: mailto:baptiste@thevelein.fr
  - title: twitter
    url: https://twitter.com/bthevelein
  - title: instagram
    url: https://instagram.com/bthevelein
  - title: github
    url: https://github.com/bthv1
  - title: linkedin
    url: https://www.linkedin.com/in/bthevelein/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
